// Generates static RSS (feed.xml) and iCalendar (cw-contests.ics) files from the
// curated database, expanded for the coming months. Regenerated by CI so the
// subscriptions stay current. Set SITE_URL for absolute links, e.g.
//   SITE_URL=https://you.github.io/cw-contest-radar npm run build-feeds
import { writeFileSync } from "node:fs";
import { CONTESTS } from "../lib/contests";
import { expandAll } from "../lib/recurrence";
import { DEFAULT_STATION, renderExchange } from "../lib/station";
import { contestById } from "../lib/contests";

const SITE = (process.env.SITE_URL || "https://example.github.io/cw-contest-radar").replace(/\/$/, "");
const DAYS_AHEAD = 150;

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
function icsTime(d: Date): string {
  return d.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
}
function pad2(n: number) {
  return n < 10 ? "0" + n : String(n);
}
function rssDate(d: Date): string {
  return d.toUTCString();
}

const now = new Date();
const to = new Date(now.getTime() + DAYS_AHEAD * 86400000);
const insts = expandAll(CONTESTS, now, to).filter((i) => i.end >= now);

// ---- RSS --------------------------------------------------------------------
const items = insts
  .slice(0, 150)
  .map((i) => {
    const c = contestById(i.contestId)!;
    const send = renderExchange(c, DEFAULT_STATION);
    const title = `${c.short} — ${i.start.getUTCDate()} ${["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][i.start.getUTCMonth()]} ${pad2(i.start.getUTCHours())}${pad2(i.start.getUTCMinutes())}Z`;
    const desc = `${c.name}. You send: ${send}. ${c.exchange.note} Bands: ${i.bands.join(", ")}m. Rules: ${c.rules}`;
    const link = `${SITE}/contests/${c.id}/`;
    return `    <item>
      <title>${esc(title)}</title>
      <link>${esc(link)}</link>
      <guid isPermaLink="false">${esc(c.id + "-" + icsTime(i.start))}</guid>
      <pubDate>${rssDate(i.start)}</pubDate>
      <description>${esc(desc)}</description>
    </item>`;
  })
  .join("\n");

const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>CW Contest Radar</title>
    <link>${esc(SITE)}/</link>
    <description>Upcoming CW contests with exchanges and rules.</description>
    <lastBuildDate>${rssDate(now)}</lastBuildDate>
    <ttl>360</ttl>
${items}
  </channel>
</rss>
`;
writeFileSync("public/feed.xml", rss);

// ---- ICS --------------------------------------------------------------------
const vevents = insts
  .map((i) => {
    const c = contestById(i.contestId)!;
    const send = renderExchange(c, DEFAULT_STATION);
    const desc = `${c.name}\\nYou send: ${send}\\n${c.exchange.note}\\nBands: ${i.bands.join(", ")}m\\nRules: ${c.rules}`;
    return [
      "BEGIN:VEVENT",
      `UID:${c.id}-${icsTime(i.start)}@cw-contest-radar`,
      `DTSTAMP:${icsTime(now)}`,
      `DTSTART:${icsTime(i.start)}`,
      `DTEND:${icsTime(i.end)}`,
      `SUMMARY:CW: ${c.short} (${c.name})`,
      `DESCRIPTION:${desc}`,
      `URL:${SITE}/contests/${c.id}/`,
      "END:VEVENT",
    ].join("\r\n");
  })
  .join("\r\n");

const ics = [
  "BEGIN:VCALENDAR",
  "VERSION:2.0",
  "PRODID:-//CW Contest Radar//EN",
  "CALSCALE:GREGORIAN",
  "METHOD:PUBLISH",
  "X-WR-CALNAME:CW Contests",
  "X-WR-TIMEZONE:UTC",
  vevents,
  "END:VCALENDAR",
].join("\r\n") + "\r\n";
writeFileSync("public/cw-contests.ics", ics);

console.log(`Wrote public/feed.xml (${insts.slice(0, 150).length} items) and public/cw-contests.ics (${insts.length} events).`);
